### ISSUE TITLE
Broken link for Multi-threading example

### ISSUE THREAD

**Issue by staypufd** [clojure-finance/clojask-examples#1]
Click on the Multi-threading example and you get taken to a page that says link not found as shown below in image.

![15467FA8-506C-48F0-BF48-27A3ABAA753E](https://user-images.githubusercontent.com/10730/172768711-2b4f2c8f-f9d3-4f33-aef1-de30bc0923d5.png)

**Comment by hkulyc** [comment]
Thank you for pointing this out. Sorry that we did not update the examples repo on time. The tutorial for multi-threading is **deprecated** by now. Clojask now can automatically pipeline the operations for different rows and columns in different threads. You only need to specify the maximum number of threads you want when calling `compute`.

**Comment by hkulyc** [comment]
#2
